### ISSUE TITLE
investigate tripduration variable

### ISSUE THREAD

**Issue by beanumber** [beanumber/citibike#15]
Is it a row index?

**Comment by vegahi** [comment]
I checked my `trip` data and the `tripduration` column is random. My `tripduration` was ordered because I did `arrange` after grouping the data. When you ran it today, I suspect that problem might come from the `PRIMARY KEY(tripduration)` in the init.mysql file. I will change the primary key to something else and see if that's the problem.

**Comment by beanumber** [comment]
Ah yes! Setting a primary key on `tripduration` also means that any duplicate rows will be discarded! 

You could maybe set a primary key on `starttime, bikeid`? I would think that the same bike cannot be rented more than once at the same time. But if that doesn't work, you may not want a primary key at all. 

However, you *should* have indexes on `bikeid`, `start_station_id` and `end_station_id`. 

We can also explore setting up a [partition scheme](https://dev.mysql.com/doc/refman/5.7/en/partitioning.html) based on the year.
